services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
     - mongo-data:/data/db
    networks:
      - app-net

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "80:5000"
    environment:
      depends_on:
        - mongo
      networks:
        - app-net

volumes:
  mongo-data:

networks:
  app-net: